# docker version 1.12.0+
# docker-compose version 1.9.0+
version: '2.1'

services:
  web:
    image: jwilder/nginx-proxy:alpine
    mem_limit: 64m
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    hostname: web
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
           - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - web-certs:/etc/nginx/certs:ro
      - web-dhparam:/etc/nginx/dhparam
      - web-vhostd:/etc/nginx/vhost.d
      - web-challenge:/usr/share/nginx/html
    restart: unless-stopped

#  web-ssl:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    mem_limit: 64m
#    hostname: web-ssl
#    domainname: ${RS_DOMAIN}
#    networks:
#      local:
#        aliases:
#           - web
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - web-certs:/etc/nginx/certs:rw
#      - web-dhparam:/etc/nginx/dhparam:rw
#      - web-vhostd:/etc/nginx/vhost.d
#      - web-challenge:/usr/share/nginx/html
#    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RS_UID: 1000
        RS_GIT_BRANCH: master
        RS_GIT_REMOTE_URL: https://github.com/sharetribe/sharetribe.git
        RAILS_ENV: production
        NODE_ENV: production
    image: roobykon/sharetribe
    mem_limit: 1024m
    hostname: app
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
          - app
    volumes:
      - app:/opt/app/www
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${PORT-3000}"]
      timeout: 300s
    restart: unless-stopped
    env_file: .env
    environment:
      - VIRTUAL_HOST=${RS_DOMAIN}
      - VIRTUAL_PORT=${PORT:-3000}
      - LETSENCRYPT_HOST=${RS_DOMAIN}
      - LETSENCRYPT_EMAIL=admin@${RS_DOMAIN}

  worker:
    image: roobykon/sharetribe
    mem_limit: 512m
    hostname: worker
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
          - sendmail
          - worker
          - search
    ports:
      - 127.0.0.1:1080:1080
    volumes:
      - app:/opt/app/www
    command: worker
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    env_file: .env

  mysql:
    image: mysql:5.7
    mem_limit: 512m
    hostname: mysql
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
          - mysql
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping"]
    restart: unless-stopped
    env_file: .env

  smtp:
    image: catatnight/postfix
    mem_limit: 64m
    hostname: smtp
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
          - smtp
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    env_file: .env

  memcache:
    image: redis:3.2-alpine
    mem_limit: 64m
    hostname: memcache
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
          - memcache
    volumes:
      - memcache:/data
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  adminer:
    image: adminer:standalone
    mem_limit: 64m
    hostname: adminer
    domainname: ${RS_DOMAIN}
    networks:
      local:
        aliases:
          - adminer
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - ADMINER_DESIGN=nicu

volumes:
  web-certs:
  web-dhparam:
  web-vhostd:
  web-challenge:
  app:
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
  mysql:
  memcache:

networks:
  local:
